name: DPV
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - cudatoolkit=11.1  # Adjust the version based on your CUDA version
  - cudnn=8.2.0  # Adjust the version based on your cuDNN version
  - tensorflow-gpu
  - pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch
  - jupyterlab
  - numpy
  - pandas
  - scikit-learn