get_mean_attention:
  attentions: "path/to/attentions.pth"
  res_dir: "path/to/results/"
  suffix: "_mean_attention"

get_integrated_gradient:
  trained_model: "path/to/trained_model.pth"
  data: "path/to/data.pth"
  target: "path/to/target.pth"
  time_seq: "path/to/time_seq.pth"
  dropout: 0.5
  hidden_dim: 128
  epochs: 50
  patience: 10
  res_dir: "path/to/results/"
  suffix: "_integrated_gradient"
  pretrained_model: "bert-base-uncased"

get_feature_importance:
  trained_model: "path/to/trained_model.pth"
  data: "path/to/data.pth"
  target: "path/to/target.pth"
  time_seq: "path/to/time_seq.pth"
  dropout: 0.5
  hidden_dim: 128
  epochs: 50
  patience: 10
  res_dir: "path/to/results/"
  suffix: "_feature_importance"
  pretrained_model: "bert-base-uncased"models.py